### ISSUE TITLE
Move all testing into a tests folder and  module

### ISSUE THREAD

**Issue by piedoom** [rust-dsp/rust-vst#24]
**TODO**
 - [x] Create Tests Directory

**Tests to move:**
 ~~[Sine Synth](https://github.com/rust-dsp/rust-vst/blob/master/examples/sine_synth.rs#L151)~~
 ~~[Main lib](https://github.com/rust-dsp/rust-vst/blob/a0ec009f1b53cb7a79f3f39cb557aa48ba7ff16f/src/lib.rs#L254)~~
- [x] [Buffer](https://github.com/rust-dsp/rust-vst/blob/a0ec009f1b53cb7a79f3f39cb557aa48ba7ff16f/src/buffer.rs#L360)
- [x] [Plugin](https://github.com/rust-dsp/rust-vst/blob/a0ec009f1b53cb7a79f3f39cb557aa48ba7ff16f/src/plugin.rs#L835)

**Tests to write:**
- [ ] dimension expander example
- [ ] simple host example
- [ ] API
- [ ] Cache
- [ ] Channels
- [ ] Editor
- [ ] Event
- [ ] Host
- [ ] Interfaces

The long term goal is to be able to self verify that the crate is functional using only the crate itself. This means having working host, and plugin examples to test with that are both verified to work.

**Comment by piedoom** [comment]
After spending more time, I have to agree with @robsaunders on this one.  Tests for private functions in the file are fine.  What do you think @zyvitski ?

**Comment by zyvitski** [comment]
Yeah that’s reasonable. We can close this. And any accompanying other items.
